### ISSUE TITLE
Add XLSX to list of output formats

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/iati-datastore#266]
### Is your feature request related to a problem? Please describe.

I _believe_ it can be a bit faffy to import CSV into Excel, particularly if the content includes non-ASCII characters.

### Describe the solution you’d like

I wonder if adding XLSX as an output format might help improve the user experience?

### Describe alternatives you’ve considered

I guess the alternative is: don’t add this feature, and just stick with CSV.

**Comment by odscjames** [comment]
To be clear: 

> adding XLSX as an output format

NOT

    Replacing CSV with XLSX

Due to a comment elsewhere I'd like to be clear.

**Comment by odscjames** [comment]
Previously we have used https://pypi.org/project/openpyxl/ but https://pypi.org/project/PyExcelerate/ has been mentioned.

**Comment by odscjames** [comment]
My colleague has also recommended https://pypi.org/project/XlsxWriter/ or https://github.com/jmcnamara/libxlsxwriter

**Comment by odscjames** [comment]
Have done https://github.com/codeforIATI/iati-datastore/pull/329 as first pull request with 2 endpoints. Future pull requests can add more endpoints and then when we are sure it's good, make the frontend changes.

To remove temp files after creation, there is a new command that should be run on cron.

When I looked online, alternatives suggested were basically use after_this_request to delete https://stackoverflow.com/a/24613980 BUT that actually deletes before the file starts sending and works because Linux lets you delete files and keep and open file handle to them, except where it goes wrong sometime and it didn't seem the worth the hassle of that hack.
