### ISSUE TITLE
Activity appearing in JSON but not XML output

### ISSUE THREAD

**Issue by markbrough** [codeforIATI/iati-datastore#273]
### Describe the bug

IATI Identifier `US-501c3-522318905-SG-112009103519` appears in the JSON output:
https://datastore.codeforiati.org/api/1/access/activity.json

But does not appear in the XML output:
https://datastore.codeforiati.org/api/1/access/activity.xml?iati-identifier=US-501c3-522318905-SG-112009103519

### To Reproduce

Steps to reproduce the behaviour:

1. Go to JSON link above
2. See that activity Identifier `US-501c3-522318905-SG-112009103519` is present 
3. Go to XML link above 
4. See that there are no results

### Expected behaviour

The same activity should appear in both places.

**Comment by andylolz** [comment]
Doesn’t appear in JSON output when using the `iati-identifier` filter either:
https://datastore.codeforiati.org/api/1/access/activity.json?iati-identifier=US-501c3-522318905-SG-112009103519

**Comment by andylolz** [comment]
Here’s that activity on d-portal:
https://d-portal.org/q.html?aid=US-501c3-522318905-SG-112009103519

Here’s the relevant dataset on the registry:
https://iatiregistry.org/dataset/aiddata-drcamp-v104

Note that it’s published by AidData.

**Comment by andylolz** [comment]
Aha okay, there are a couple of issues here.

Here’s the value in the source data:
![Screenshot 2021-08-15 at 17 51 49](https://user-images.githubusercontent.com/464193/129486141-5e5301a5-28f7-43fd-89cd-a5624e9a8317.png)

There’s a lot of whitespace around the identifier. I think that’s what is causing the issue here. If you search for the IATI identifier with the whitespace, it works:
https://datastore.codeforiati.org/api/1/access/activity.xml?iati-identifier=%0A%09%09%09US-501c3-522318905-SG-112009103519%0A%09%09

---

However, it’s weird that this whitespace is stripped from the JSON output. That seems like a bug.

**Comment by andylolz** [comment]
> However, it’s weird that this whitespace is stripped from the JSON output. That seems like a bug.

Okay, so if you use:
https://datastore.codeforiati.org/api/1/access/activity.db.json

…you get a more accurate representation of the IATI identifier (i.e. without the whitespace stripped):

```json
{
    "iati-activities": [
        {
            "activity-website": [],
            "budget": {},
            "description": "",
            "end-actual": null,
            "end-planned": null,
            "iati-identifier": "\n\t\t\tUS-501c3-522318905-SG-112009103519\n\t\t",
            "last-change": "2021-07-27"
            ...
        }
    ],
    "limit": 50,
    "ok": true,
    "start": 0,
    "total-count": 1070422
}
```

Whitespace stripping is courtesy of [xmltodict](https://pypi.org/project/xmltodict/) it seems.

**Comment by andylolz** [comment]
Okay this now looks awful (because of data issues) but it’s no longer adulterated by the JSON serializer: https://datastore.codeforiati.org/api/1/access/activity/?iati-identifier=%0A%09%09%09US-501c3-522318905-SG-112009103519%0A%09%09
