### ISSUE TITLE
Convert and export data in USD

### ISSUE THREAD

**Issue by markbrough** [codeforIATI/iati-datastore#335]
### Is your feature request related to a problem? Please describe.

Currently, financial data is stored in a range of currencies, depending on the currency of the original publisher. For data users accessing the data in CSV, it would be helpful to have the data available in a standard currency, probably USD.

### Describe the solution you’d like

* Convert financial data to USD when parsing data into Datastore Classic
* Export USD value column in CSV exports

### Describe alternatives you’ve considered

Using CDFD: https://countrydata.iatistandard.org

This converts data into USD, EUR and a local currency for the relevant recipient country.

See here for more details on the methodology:
https://countrydata.iatistandard.org/methodology/#_2-5-currency-conversion

**Comment by markbrough** [comment]
See here for exchange rates data:
https://github.com/codeforIATI/imf-exchangerates/

**Comment by odscjames** [comment]
Convert with exchange rate on day of transaction, repo above has historic data

**Comment by stevieflow** [comment]
@markbrough please can you point to the code/process you use for IATI spreadsheets, please?

**Comment by stevieflow** [comment]
@kindly may have also done this with IATI tables...

**Comment by markbrough** [comment]
Can use this library (but make sure to point it at the imf-exchangerates dataset):
https://pypi.org/project/exchangerates/

`value-date/@iso-date`

**Comment by odscjames** [comment]
Publishers may have not used a real code; in this case leave USD values as NULL

**Comment by stevieflow** [comment]
> day of transaction

I think we have to use value-date for the exchange rate - not the iso-date.  The value-date element is specifically there for exchange rate purposes

**Comment by stevieflow** [comment]
@markbrough whilst we are here, any reason why we should not convert to EUR, and possibly XDR too?

(I think https://countrydata.iatistandard.org/ converts to USD and EUR?)

**Comment by radix0000** [comment]
The currency conversion code is generally done (at least for USD) but there are a number of cases where decisions need to be made about what is best to do. About 10% of transactions are not being converted at the moment.

Some rough statistics below:

- Total Transactions: 8,686,489
- Total Null USD Value: 768,596
- Value amount is zero: 444,346
- Value amount non-zero: 297,311
- After IMF data ends: 279,063
- Future date: 297
- Value currency not found: 16,515
- Default currency null: 15472
- Default code not found: 140

<p>Value currency not found:</p>

| Currency Code | Occurrences | Notes|
| -- | -- | -- |
| NAD | 9 | Namibian dollar (not in IMF data) |
| XBT | 1 | Bitcoin (not in IMF data) |
| BEF | 476 | Belgian franc (date?) |
| USS | 7 | US Dollar (Same day) |
| HTG | 2 | Haitian Gourde |
| SLL | 210 | Sierra Leonean leone (code changed - SLE?) |
| USN | 1 | US dollar (next-day) |
| EURO | 1 | code wrong |
| ZMK | 185 | Zambian kwacha replaced with the new Zambian Kwacha (ZMW) on January 1, 2013 |
| FKP | 5 | Falkland Islands pound (one-to-one with sterling) |
| NULL | 15573 |  |

<p>Default currency not found:</p>

| Currency Code | Occurrences |
| -- | -- |
| SLL | 63 |
| USS | 5 |

**Comment by radix0000** [comment]
Over half of the unconverted values are due to the fact the transaction value is zero. My feeling is that it is best to output a null value for these rather than zero, but there may be other opinions? It might partially depend on what the intention, if any, of having transactions with zero values is.

**Comment by radix0000** [comment]
The vast majority of the rest are because the date is after the end of the IMF data. There are a few where the date is actually in the future but mostly it is because the date is in the last month or so after IMF data stops. There is definitely a decision needed about how to handle these. Setting them to null for moment and only convert when IMF data turns up seems like the least bad option? Having a provisional number in there sourced from somewhere else, which then might change under people at a later date doesn't seem like a good approach.

Need to look into whether that lag in IMF data is intrinsic to IMF or whether a significant fraction of it is being introduced by going via imf_exchangerates.csv. But this is a problem that is likely to always exists, and needs to be dealt with, even if it can be made smaller by going straight to IMF.

**Comment by radix0000** [comment]
There are a smattering of cases where there are issues related to not finding currency codes, some of which may be fixable with some tweaking, some not. How much effort to put into picking off these issues with small numbers of codes, is a question though?

**Comment by stevieflow** [comment]
Thanks @radix0000 - really helpful

> My feeling is that it is best to output a null value for these rather than zero, but there may be other opinions?

I think if a transaction has a value of zero (0) then we can also convert that to USD 0.  I think there are some arrangements whereby publishers are providing these types of activities, just to indicate that there has been no monetary flow.  Agree @markbrough @andylolz  ? 

> The vast majority of the rest are because the date is after the end of the IMF data.

I think the preference here would be to use the last available IMF rate.  I then accept that this means that some values will change, as the IMF data is updated.  We briefly discussed having a flag in the data to indicate that this value may change --> but for now, I think having any value (rather than null, would be preferable.  Agree @markbrough @andylolz ? @bill-anderson might also have an insight on this...

> There are a few where the date is actually in the future

and/or the date doesn't exist - eg: 31st Sept: https://d-portal.org/ctrack.html#view=act&aid=41119-UA-S2-RT

In these instances, I think this is bad data, and cannot be converted to USD.  We should not find workarounds. Agree @markbrough @andylolz ?  I think @davidmegginson may also support this idea

> There are a smattering of cases where there are issues related to not finding currency codes

I think this is also "bad data", and would avoid workarounds, at this moment (maybe we look at that later - maybe not)

Also pinging @HermanvanLoon as I think he'd be interested in these validation / data quality issues.  I can replicate some of this onto IATI connect

**Comment by HermanvanLoon** [comment]
I.m.o. there is nor one "correct" way to do currency conversions. There are many different ways currencies can be converted (spot rates, yearly average rates, etc.). There are also many providers of currency information (e.g. Reuters, IMF, ECB, etc.), Also what to do with budgets which span a period instead of being a point in time. And to what currency to convert. USD is fine, but for our purposes we need EUR. So that begs the question if currency conversion should be part of the IATI datastore and if so, what methodology and provider should be chosen. I doubt that there will be 'one size fits all' solution. 

Concerning 0 transaction amounts: I would convert those to zero USD or EUR amounts. A zero amount has been defined so it can be converted. I remember though from the past that it was seen as bad practice to publish zero amounts.

Concerning future dates not in the currency table: in our system we solve that by using the most recent exchange rate available for a given currency and extend that into the future.

**Comment by davidmegginson** [comment]
I will just add my voice that it's always valuable to make a distinction between 0 (an actual number) and null (data missing/unavailable/unusable). I don't think I saw any disagreement in the thread, but just checking in.

**Comment by andylolz** [comment]
> The currency conversion code is generally done

@radix0000 Is there a (draft?) pull request? I’m not sure I understand what [the statistics in this post](https://github.com/codeforIATI/iati-datastore/issues/335#issuecomment-1282037598) relate to exactly – some code would probably help.

**Comment by davidmegginson** [comment]
> > The currency conversion code is generally done
> 
> @radix0000 That’s great news! Is there a (draft?) pull request? I’m not sure I understand what [the statistics in this post](https://github.com/codeforIATI/iati-datastore/issues/335#issuecomment-1282037598) relate to exactly – some code would probably help.

All our code's public, so if you don't mind a little digging, you can start here: https://github.com/OCHA-DAP/hdx-scraper-iati-viz

**Comment by markbrough** [comment]
Here are my proposals for how we handle each of these issues:

Issue | Solution
--- | ---
Total Null USD Value | null
Value amount is zero | 0
After IMF data ends | Use most recent date
Future date | Use most recent date
Value currency not found | null -> handle this in [codeforIATI/imf-exchangerates/](https://github.com/codeforIATI/imf-exchangerates/)
Default currency null | null
Default code not found | null

I think the null values should work OK for use in Excel as you can easily filter out all `(blank)` values. But we can see how this works later.

@HermanvanLoon agreed that there is not one "correct" way to do currency conversion -- but I think providing this as an option for users to use in the data will significantly lower barriers to use, compared with requiring each user to establish a methodology and convert every value themselves. I think using IMF exchange rates data is reasonable. Though I think we can debate whether conversion against monthly averages or the closest rate to the end of the period (month) is more reasonable; both are available through [codeforIATI/imf-exchangerates/](https://github.com/codeforIATI/imf-exchangerates/) so it would be easy to swap out the methodology here.

I think it would be useful to also convert to EUR. I created a new issue for conversion to EUR: https://github.com/codeforIATI/iati-datastore/issues/378 -- if it's easy to solve that issue at the same time, let's add it in now, but if not, we shouldn't hold up deploying USD conversion as quickly as possible.

**Comment by radix0000** [comment]
@andylolz I have created a couple of draft pull requests for the USD currency conversion (first one with most of code and second with changes to parser to be merged afterwards), so you can take a look at code. 

@markbrough It should be pretty simple to add EUR conversions as well, I will take a look.

**Comment by markbrough** [comment]
Closed in https://github.com/codeforIATI/iati-datastore/pull/385#event-7893844462
